---
abstract: 'Use MongoDB within Kelp'
author:
  - 'Adam Stokes <adam.stokes@ubuntu.com>'
build_requires:
  Kelp: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Kelp-Module-MongoDB
requires:
  Kelp::Base: 0
  MongoDB: 0
resources:
  homepage: https://github.com/battlemidget/Kelp-Module-MongoDB
  repository: https://github.com/battlemidget/Kelp-Module-MongoDB.git
version: 0.001
