---
abstract: 'Use MongoDB within Kelp'
author:
  - 'Adam Stokes <adamjs@cpan.org>'
build_requires: {}
configure_requires:
  Module::Build::Tiny: 0.026
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.4, Dist::Zilla version 4.300037, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Kelp-Module-MongoDB
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Kelp: 0
  Kelp::Base: 0
  MongoDB: 0
resources:
  bugtracker: https://github.com/battlemidget/Kelp-Module-MongoDB/issues
  homepage: https://github.com/battlemidget/Kelp-Module-MongoDB
  repository: https://github.com/battlemidget/Kelp-Module-MongoDB.git
version: 1.000
x_contributors:
  - 'Adam Stokes <adam.stokes@ubuntu.com>'
